import { type NextPage } from "next";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
// import Link from "next/link";
import { api } from "~/utils/api";
import { Link } from "@chakra-ui/next-js";
import { Text, Box, Heading, Grid, GridItem, Spacer } from "@chakra-ui/react";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box minH={"100vh"}>
        <Heading
          textAlign={"center"}
          margin={10}
          as={"h1"}
          size={"4xl"}
          className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]"
        >
          My <span className="text-[hsl(280,100%,70%)]">Boilerplate</span>
        </Heading>
        <AuthShowcase />
        <Grid
          gap={[4, null, 1]}
          templateColumns={["repeat(1, 1fr)", null, "repeat(2, 1fr)"]}
          className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8"
          justifyItems={"center"}
          alignItems={"center"}
        >
          <GridItem
            backgroundColor={"rgba(255, 255, 255, 10%)"}
            _hover={{ backgroundColor: "rgba(255, 255, 255, 20%)" }}
            padding={"30px 20px"}
            borderRadius={15}
            margin={"10px 20px"}
            minH={"180px"}
            width={"85%"}
          >
            <Link
              display={"flex"}
              flexDirection={"column"}
              href="https://create.t3.gg/en/usage/first-steps"
              target="_blank"
            >
              <Heading as={"h3"} size={"xl"} className="text-2xl font-bold">
                First Steps →
              </Heading>
              <Text fontSize={"xl"} className="text-lg">
                Just the basics - Everything you need to know to set up your
                database and authentication.
              </Text>
            </Link>
          </GridItem>
          <GridItem
            backgroundColor={"rgba(255, 255, 255, 10%)"}
            _hover={{ backgroundColor: "rgba(255, 255, 255, 20%)" }}
            padding={"30px 20px"}
            margin={"10px 20px"}
            borderRadius={15}
            minH={"180px"}
            width={"85%"}
          >
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://chakra-ui.com/"
              target="_blank"
            >
              <Heading as={"h3"} size={"xl"} className="text-2xl font-bold">
                Chakra-UI →
              </Heading>
              <Text fontSize={"xl"} className="text-lg">
                Learn more about chakra-ui and its components.
              </Text>
            </Link>
          </GridItem>
          <GridItem
            backgroundColor={"rgba(255, 255, 255, 10%)"}
            _hover={{ backgroundColor: "rgba(255, 255, 255, 20%)" }}
            padding={"30px 20px"}
            margin={"10px 20px"}
            borderRadius={15}
            minH={"180px"}
            width={"85%"}
          >
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/introduction"
              target="_blank"
            >
              <Heading as={"h3"} size={"xl"} className="text-2xl font-bold">
                Documentation →
              </Heading>
              <Text fontSize={"xl"} className="text-lg">
                Learn more about Create T3 App, the libraries it uses, and how
                to deploy it.
              </Text>
            </Link>
          </GridItem>
          <GridItem
            backgroundColor={"rgba(255, 255, 255, 10%)"}
            _hover={{ backgroundColor: "rgba(255, 255, 255, 20%)" }}
            padding={"30px 20px"}
            margin={"10px 20px"}
            borderRadius={15}
            minH={"180px"}
            width={"85%"}
          >
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://github.com/crimson-med"
              target="_blank"
            >
              <Heading as={"h3"} size={"xl"} className="text-2xl font-bold">
                Mederic Burlet →
              </Heading>
              <Text fontSize={"xl"} className="text-lg">
                Author of this t3 template with chakra ui. You can find me on
                github.
              </Text>
            </Link>
          </GridItem>
        </Grid>
      </Box>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.example.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined }
  );
  console.log("session");
  console.log(sessionData);

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
    </div>
  );
};
